name = "super"
version = "1.0.0"
description = "A Gleam project that depends on many other Gleam projects"
target = "erlang"

[dependencies]
gleam_stdlib = "~> 0.26"
gleam_http = "~> 3.1"
gleam_httpc = "~> 2.0"
gleam_erlang = "~> 0.18"
gleam_otp = "~> 0.5"
gleam_json = "~> 0.5"
mist = "~> 0.9"
glisten = "~> 0.6"
shellout = "~> 1.1"
gleam_crypto = "~> 0.3"
gleam_mongo = "~> 0.13"
gleam_pgo = "~> 0.4"
birl = "~> 0.4"
gleam_sendgrid = "~> 0.1"
snag = "~> 0.2"
minigen = "~> 0.0"
gleam_cors = "~> 0.2"
glog = "~> 0.2"
gleam_bson = "~> 0.20"
gap = "~> 0.1"
glance = "~> 0.5"
gleam_hackney = "~> 1.0"
espresso = "~> 0.0"
simplifile = "~> 0.1"
trie_again = "~> 1.1"
gliew = "~> 0.3"
glerm = "~> 0.1"
nibble = "~> 0.2"
globe = "~> 0.1"
glove = "~> 0.2"
glenvy = "~> 0.4"
glx = "~> 0.2"
ream = "~> 0.1"
non_empty_list = "~> 1.0"
nakai = "~> 0.8"
gleamy_structures = "~> 0.3"
gsv = "~> 0.1"

[dev-dependencies]
gleeunit = "~> 0.10"
