name = "super"
version = "1.0.0"
description = "A Gleam project that depends on many other Gleam projects"
target = "erlang"

[dependencies]
gleam_stdlib = "~> 0.26"
gleam_http = "~> 3.1"
gleam_httpc = "~> 2.0"
gleam_hackney = "~> 0.2"
gleam_erlang = "~> 0.18"
gleam_otp = "~> 0.5"
gleam_json = "~> 0.5"
mist = "~> 0.9"
glisten = "~> 0.6"
shellout = "~> 1.1"
glint = "~> 0.11"
gleam_crypto = "~> 0.3"
gleam_mongo = "~> 0.13"
gleam_pgo = "~> 0.4"
birl = "~> 0.4"
gleam_sendgrid = "~> 0.1"
snag = "~> 0.2"
minigen = "~> 0.0"
gleam_cors = "~> 0.1"
glog = "~> 0.2"
emel = "~> 1.0"
nibble = "~> 0.2"
gleam_bson = "~> 0.20"
gap = "~> 0.1"

[dev-dependencies]
gleeunit = "~> 0.10"
