[package]
name = "hexpm"
version = "1.0.0"
authors = ["Louis Pilfold <louis@lpil.uk>"]
edition = "2018"

readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/gleam-lang/hexpm-rust"
description = "A Rust client for the Hex package manager"
keywords = ["erlang", "gleam", "elixir", "hex", "api-client"]
categories = ["api-bindings"]

[dependencies]
# HTTP client
reqwest = { version = "0.10", features = ["json"] }
# Derive Error trait
thiserror = "1.0"
# JSON (de)serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# HTTP types
url = "2.1"
http = "0.2"
# Macro to have async fns in traits
async-trait = "0.1"
# Complex static values
lazy_static = "1.4"
# Text parsing with regular expressions
regex = "1.3.7"
# Byte collections
bytes = "0.5"

[dev-dependencies]
# HTTP mock server
mockito = "0.25.1"
# Async runtime
tokio = { version = "0.2", features = ["full"] }
