[package]
name = "gleam"
version = "0.11.1"
authors = ["Louis Pilfold <louis@lpil.uk>"]
edition = "2018"

[dependencies]
# OS SIGINT and SIGTERM signal handling
ctrlc = { version = "3.0", features = ["termination"] }
# Command line interface
clap = "2"
structopt = "0.3"
# Immutable data structures
im = "15"
# Extra iter methods
itertools = "0.9"
# String case conversion
heck = "0.3"
# Parsing
lalrpop-util = "0.19"
regex = "1.1"
# Graph data structures
petgraph = "0.5"
# Pretty error messages
codespan = "0.9"
codespan-reporting = "0.9"
termcolor = "1.0"
# Initialize complex static values at runtime
lazy_static = "1.3"
# toml parsing
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
toml = "0.5"
# Levenshtein string distance for typo suggestions
strsim = "0.10"
# Recursively traversing directories
ignore = "0.4"
walkdir = "2"
# Enum trait impl macros
strum = "0.19"
strum_macros = "0.19"
# Doc rendering
askama = "0.10"
# Markdown in docs
pulldown-cmark = "0.7"
# Support unicode in gleam source
unicode-segmentation = "1.6"
# Check for tty
atty = "0.2"
# Hex package manager client
hexpm = "1.1"
# Allow user to type in sensitive information without showing it in the shell
rpassword = "5.0"
# Async runtime
tokio = "0.2"
# Creation of tar file archives
tar = "0.4"
# gzip compression
flate2 = "1.0"
# Byte array data type
bytes = "0.5"
# Further file system functions (i.e. copy directory)
fs_extra = "1.1"
# Logging
tracing = "0.1"
tracing-subscriber = "0.2"

[build-dependencies]
serde_derive = "1.0"
lalrpop = { version = "0.19", features = ["lexer"] }

[dev-dependencies]
pretty_assertions = "0.6"
