[package]
name = "gleam"
version = "0.8.0-dev"
authors = ["Louis Pilfold <louis@lpil.uk>"]
edition = "2018"

[dependencies]
# Command line interface
clap = "2"
structopt = "0.3"
# Immutable data structures
im = "14"
# Extra iter methods
itertools = "0.8"
# String case conversion
heck = "0.3"
# Parsing
lalrpop-util = "0.17"
regex = "1.1"
# Graph data structures
petgraph = "0.4"
# Pretty error messages
codespan = "0.7"
codespan-reporting = "0.7"
termcolor = "1.0.4"
# Initialize complex static values at runtime
lazy_static = "1.3"
# toml parsing
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"
# Levenshtein string distance for typo suggestions
strsim = "0.9"
# Recursively traversing directories
walkdir = "2"
# Enum trait impl macros
strum = "0.17"
strum_macros = "0.17"
# Doc rendering
askama = "0.8"
# Markdown in docs
pulldown-cmark = "0.7.0"

[build-dependencies]
lalrpop = "0.17"

[dev-dependencies]
pretty_assertions = "0.6"
