[package]
name = "gleam-wasm"
version = "0.17.0-rc2"
authors = ["Louis Pilfold <louis@lpil.uk>"]
edition = "2018"
license-file = "LICENCE"

[lib]
# This package compiles to wasm
crate-type = ["cdylib", "rlib"]

[dependencies]
gleam-core = { path = "../compiler-core" }
wasm-bindgen = "0.2"

[dev-dependencies]
wasm-bindgen-test = "0.2"
