[package]
authors = ["Louis Pilfold <louis@lpil.uk>"]
edition = "2021"
license-file = "LICENCE"
name = "gleam-wasm"
version = "0.18.0-rc2"

[lib]
# This package compiles to wasm
crate-type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
gleam-core = {path = "../compiler-core"}
hexpm = "1.4.0"
log = "*"
rust-embed = {version = "6.2.0", features = ["debug-embed"]}
serde = {version = "1.0", features = ["derive"]}
wasm-bindgen = {version = "0.2", features = ["serde-serialize"]}
wasm-logger = "0.2.0"

[dev-dependencies]
wasm-bindgen-test = "0.3.28"
