blank_issues_enabled: false
contact_links:
  - name: Gleam GitHub Discussions
    url: https://github.com/gleam-lang/gleam/discussions
    about: Discuss proposals, ask and answer questions here.
  - name: Gleam Community Discord
    url: https://discord.com/invite/Fm8Pwmy
    about: Discuss proposals, ask and answer questions here.
  - name: The language tour
    url: https://gleam.run/book/tour/
    about: An introduction to Gleam language features
  - name: Gleam Playground
    url: https://johndoneth.github.io/gleam-playground/
    about: Great for trying Gleam code in your browser and for sharing small bits of code
  
