[package]
name = "gleam"
version = "0.22.0-dev"
authors = ["Louis Pilfold <louis@lpil.uk>"]
edition = "2021"
license-file = "LICENCE"

[dependencies]
# The pure compiler
gleam-core = { path = "../compiler-core" }
# Immutable data structures
im = "15.0.0"
# OS SIGINT and SIGTERM signal handling
ctrlc = { version = "3.2.1", features = ["termination"] }
# Command line interface
clap = { version = "3.0", features = ["derive"] }
# Extra iter methods
itertools = "0.10.1"
# Parsing
regex = "1.5.4"
# Colours in terminal
termcolor = "1.1.2"
# Initialize complex static values at runtime
lazy_static = "1.4.0"
# Data (de)serialisation
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "*"
# toml config file parsing
toml = "0.5.8"
# Recursively traversing directories
ignore = "0.4.18"
walkdir = "2.3.2"
# Enum trait impl macros
strum = { version = "0.24.0", features = ["derive"] }
# Check for tty
atty = "0.2.14"
# Hex package manager client
hexpm = "2.0.0"
# Allow user to type in sensitive information without showing it in the shell
rpassword = "5.0.1"
# Async runtime
tokio = { version = "1.14.0", features = ["rt", "rt-multi-thread"] }
# Creation of tar file archives
tar = "0.4.37"
# gzip compression
flate2 = "1.0.22"
# Byte array data type
bytes = "1.1.0"
# Further file system functions (i.e. copy directory)
fs_extra = "1.2.0"
# Logging
tracing = "0.1.29"
tracing-subscriber = { version = "0.3.2", features = ["fmt", "env-filter"] }
# HTTP client
reqwest = "0.11.6"
# Macro to work around Rust's traits not working with async. Sigh.
async-trait = "0.1.51"
# HTTP types
http = "0.2.5"
# Async combinators for futures
futures = "0.3.17"
# Little helper to omit fields that cannot be debug printed
debug-ignore = "1.0.1"
# Checksums
sha2 = "0.9.8"
# Getting hostname
hostname = "0.3.1"
# base encoding
base16 = "0.2.1"
# TOML parser/editor that preserves comments & formatting
toml_edit = "0.9"
# Cross platform symlink creation helper
symlink = "0.1"
# Language server protocol server plumbing
lsp-server = "0.5"
lsp-types = "0.92"
# File locking
fslock = "0.2.1"

[target.'cfg(target_os = "windows")'.dependencies]
# File URl decoding
urlencoding = "2.1.0"

[dev-dependencies]
# Test assertion errors with diffs
pretty_assertions = "1.0.0"
