[package]
name = "gleam"
version = "0.17.0-dev"
authors = ["Louis Pilfold <louis@lpil.uk>"]
edition = "2018"
license-file = "LICENCE"

[dependencies]
# The pure compiler
gleam-core = { path = "../compiler-core" }
# OS SIGINT and SIGTERM signal handling
ctrlc = { version = "3.1.7", features = ["termination"] }
# Command line interface
structopt = "0.3.21"
# # Immutable data structures
# im = "15.0.0"
# Extra iter methods
itertools = "0.10.0"
# Parsing
regex = "1.4.3"
# Colours in terminal
termcolor = "1.1.2" 
# Initialize complex static values at runtime
lazy_static = "1.4.0"
# Data (de)serialisation
serde = { version = "1.0.119", features = ["derive"] }
# toml config file parsing
toml = "0.5.8"
# Recursively traversing directories
ignore = "0.4.17"
walkdir = "2.3.1"
# Enum trait impl macros
strum = { version = "0.20.0", features = ["derive"] }
# Check for tty
atty = "0.2.14"
# Hex package manager client
hexpm = "1.3.0"
# Allow user to type in sensitive information without showing it in the shell
rpassword = "5.0.0"
# Async runtime
tokio = { version = "1.0.1", features = ["rt", "rt-multi-thread"] }
# Creation of tar file archives
tar = "0.4.30"
# gzip compression
flate2 = "1.0.19"
# Byte array data type
bytes = "1.0"
# Further file system functions (i.e. copy directory)
fs_extra = "1.2.0"
# Logging
tracing = "0.1.22"
tracing-subscriber = "0.2.15"

[dev-dependencies]
# Test assertion errors with diffs
pretty_assertions = "0.7"
